---
title: "Impact of Nozzle Temperature on Strength of Final Print"
description: |
  These graphs will discuss the impact that the nozzle temperature will have on a 3D print.
author:
  - name: Anmay Gupta
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(dplyr)
library(knitr)
library(rmarkdown)
library(plotly)
```


Explanation as to what nozzle temperature actually is.

```{r select_data}
data <- read_rds("data.rds")
clean_data <- data %>%
                select(nozzle_temperature, roughness, material, tension_strength, elongation) %>%
                arrange(nozzle_temperature) %>% 
                mutate(trial_number = row_number()) %>%
                mutate(is_rough = roughness > 200)
```

Effect of Nozzle Temperature on Roughness:

```{r roughness}
roughness <- clean_data %>%
               ggplot(aes(x = trial_number, y = roughness, fill = nozzle_temperature)) +
               geom_col() +
               facet_wrap(~ material) +
               geom_smooth(method = "loess", formula = "y ~ x", se = FALSE) + 
               labs(title = "Effect of Nozzle Temperature on Roughness",
                    subtitle = "PLA prints have a higher quality at a lower temperature while\nABS prints have a higher quality at a higher temperature.",
                    x = "Trial Number",
                    y = "Roughness (µm)",
                    fill = "Nozzle Temperature (mm)",
                    caption = "Source: Selcuk University, February 26th 2019")
roughness
ggsave("images/nozzle1.png", roughness)
```

Effect on Tension Strength:

```{r tension}
tension <- clean_data %>%
             ggplot(aes(x = trial_number, y = tension_strength, fill = nozzle_temperature)) +
             geom_col() +
             facet_wrap(~ material) +
             geom_smooth(method = "loess", formula = "y ~ x", se = FALSE) + 
             labs(title = "Effect of Nozzle Temperature on Tension Strength",
                    subtitle = "PLA prints have a higher strength at a higher temperature while\nABS prints have a higher strength at a medium temperature.",
                  x = "Trial Number",
                  y = "Tension Strength (MPa)",
                  fill = "Nozzle Temperature (mm)",
                  caption = "Source: Selcuk University, February 26th 2019")
tension
ggsave("images/nozzle2.png", tension)
```

Effect on Elongation:

```{r elongation}
elongon <- clean_data %>%
             ggplot(aes(x = trial_number, y = elongation, fill = nozzle_temperature)) +
             geom_col() +
             facet_wrap(~ material) +
             geom_smooth(method = "loess", formula = "y ~ x", se = FALSE) + 
             labs(title = "Effect of Nozzle Temperature on Elongation Percentage",
                  subtitle = "PLA prints deform more at a higher temperature while\nABS prints deform less at a higher temperature.",
                  x = "Trial Number",
                  y = "Elongation (%)",
                  fill = "Nozzle Temperature (mm)",
                  caption = "Source: Selcuk University, February 26th 2019")
elongon
ggsave("images/wall3.png", elongon)
```


